### ISSUE TITLE
Error while combining

### ISSUE THREAD

**Issue by tomascharad** [boazsegev/combine_pdf#104]
Dear Bo,

Thanks for keeping up with this amazing library!

I think I might have found a bug probably related with a strange pdf format.

Here I enclose the pdfs so you can reproduce, you have to combine them in that order:
1. https://slack-files.com/T0CCB44TF-F4N5XDW49-22997ade80
2. https://slack-files.com/T0CCB44TF-F4NPUBZCK-d1e412c01e

The stacktrace is the following:

```TypeError: no implicit conversion of nil into Hash
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `merge'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `hash_merge_new_no_page'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `merge'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `hash_merge_new_no_page'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `merge'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `hash_merge_new_no_page'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `merge'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_protected.rb:228:in `hash_merge_new_no_page'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_public.rb:304:in `update'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_public.rb:304:in `insert'
/app/vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.32/lib/combine_pdf/pdf_public.rb:274:in `<<'

**Comment by boazsegev** [comment]
Hi Tomás,

Thanks for exposing this issue!

I can confirm that the merging of the PDF files fails with the error `TypeError: no implicit conversion of nil into Hash`

I'm somewhat swamped, as I have two big projects due Monday, but I'll try to fix it this weekend or early this week.

Thanks again 👍🏻

Have an amazing weekend!
Bo.

**Comment by boazsegev** [comment]
Hi... P.S.

I committed a possible fix, but I don't have the time to run all the tests at the moment. I'd love it if you could try the patched version and see if it works better for you. I'll test this later.

B.

**Comment by tomascharad** [comment]
@boazsegev,

I can confirm that the last version (0.2.36) Works flawlessly.
Many thanks!

**Comment by boazsegev** [comment]
Cool 👍🏻

Thanks for letting me know.

If this version doesn't experience any new issues in the next two weeks or so, I might release it as version 1.0 ... I think the gem was using the development versioning system for too long. The API is quite stable by now.

Thanks again 👍🏻
