### ISSUE TITLE
Single pdf causing to_pdf to hang forever

### ISSUE THREAD

**Issue by ThunderGuppy** [boazsegev/combine_pdf#107]
We're run into a strange issue, wherein a particular pdf from our production server is causing an infinite hang when being generated into a pdf.

Code snippet is as follows:

```
def create_pdf_package
    combined_pdf = CombinePDF.new
    add_schedule_docs_to_pdf_package(combined_pdf)
    add_all_pdfs_docs_to_pdf_package(combined_pdf)
    # Suddenly decides to just stop dead right here
    combined_pdf.to_pdf
  end

def add_all_pdfs_docs_to_pdf_package(combined_pdf)
    all_pdf_docs.each do |doc|
      pdf_data = doc.document.data
      begin
        combined_pdf << CombinePDF.parse(pdf_data, allow_optional_content: true)
      rescue => e
        Rails.logger.info "[PDF PACKAGE ERROR] Couldn't add #{doc&.document&.name} (#{doc&.title}) to package in project #{project.id}: #{e.message}"
        raise PdfPackageGenerationError.new(doc)
      end
    end
  end
```

If I give you the problem pdf in question, might you be able to provide some insight into what is causing this?

**Comment by boazsegev** [comment]
Hi @ThunderGuppy ,

Thank you very much for opening this issue.

I would love to have a look and hopefully resolve this issue.

Could you send me the PDF in question and minimal working example code, so I can replicate the issue on my machine, that would be great!

Thanks again,
  Bo.

**Comment by boazsegev** [comment]
Did the latest release resolve the issue (v. 1.0.0)?

**Comment by boazsegev** [comment]
I can't reproduce the issue with the new gem version. If you still experience issues, please reopen.

**Comment by edsontrick** [comment]
I can reproduce with the actual gem version 👍 
[test.pdf](https://github.com/user-attachments/files/16255044/test.pdf)

Just use this pdf
