### ISSUE TITLE
Skips Style

### ISSUE THREAD

**Issue by emmanuelmillionaer** [boazsegev/combine_pdf#108]
Hi @boazsegev ! 🙂  Thanks for this great gem, it's nice to use. 

I try to combine a pdf but when I run it, I get this warnings:

```
.....
Advancing for unknown reason... 3 5 b 2  ... b 2 
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason...  2 4> >> ... > >>
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason... ose < 0  ... < 0 
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason...  2 4> >> ... > >>
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason... ose < 0  ... < 0 
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason...  2 4> >> ... > >>
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason... ose < 0  ... < 0 
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason... 3 5 b 2  ... b 2 
Warning: parser advancing for unknown reason. Potential data-loss.
Advancing for unknown reason...  2 4> >> ... > >>
Warning: parser advancing for unknown reason. Potential data-loss.
.....
````

The result is, that I get a new PDF returned, with the tables, images etc. But all the text is missing. 
I opened the PDF in a Text-Editor:

```
<</Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>>
endobj
34 0 obj
<</Type /FontDescriptor
/FontName /MPDFAA+DejaVuSerifCondensed-Italic
 /CapHeight 729
 /XHeight 519
 /FontBBox [-755 -347 1480 1109]
 /Flags 68
 /Ascent 928
 /Descent -236
 /Leading 0
 /ItalicAngle -11
 /StemV 87
 /MissingWidth 540
 /Style << /Panose < 0 0 2 6 6 6 5 3 5 b 2 4> >>
/FontFile2 36 0 R
>>
```

Basically where I think it fails is in this line:

`/Style << /Panose < 0 0 2 6 6 6 5 3 5 b 2 4> >>`

@boazsegev do you know what `Panose` in the PDF defines and  if there is maybe a solution for this issue? 🙂  Thanks for your help 👍

**Comment by boazsegev** [comment]
Hi @emmanuelmillionaer ,

Thank you very much for opening and exposing this issue.

The `Panose` information should be passed through untouched, along with the `FontDescriptor` and it's children.

However, it seems this might not be the case, so I will need to deep a bit deeper.

Could you send me an example PDF file where this happens, so I can test the issue and different patches?

Thanks!
   Bo.

**Comment by emmanuelmillionaer** [comment]
Hi @boazsegev  🙂  

thanks for your efforts. 

In the PDF's there is some confidential information included. I'm not allowed to release this information. That's why I tried to split the PDF's and only send you public accessible pages or modify the contents. I tried different software for that. The issue with this approach is, that afterwards the PDF's do not anymore include this line `/Style << /Panose < 0 0 2 6 6 6 5 3 5 b 2 4> >>`, where the error seems to appear.

I would really like to help to fix this bug, could you maybe give me an advice what to try out in the `parser.rb` to pass this information, like you said? 🙂  Thanks again for this awesome gem! 💯

**Comment by boazsegev** [comment]
I have a two main things I want to work on when trying to fix this:

1. The current parser doesn't expect spaces in the hex representation of the string object (the `<0000020606 ...>` is a hex representation of a PDF string object)... so in `parser.rb`, line 231, we might add the `\s` option to the Regexp, so it looks like this (Don't do that, though, because of issue number 2):

 ```ruby
 elsif str = @scanner.scan(/<[0-9a-fA-F\s]*>/)
 ```

2. But your PDF is a bit malformed. The Hex representation isn't zero delimited, so `6` might mean `60` (which seems to be what the Ruby `unpack` function thinks) and it might mean `06` (which is what I would assume)...

 ... these missing zeros mean that the parser would have to take additional steps when spaces are used within a string.

 So, instead of editing line 231 in `parser.rb`, I would add a special case for space delimited hex strings, leaving the simple case in place (for quick processing) and maybe do something like this (these are lines 228-239):

```ruby
        elsif str = @scanner.scan(/<[0-9a-fA-F]*>/)
          # warn "Found a hex string"
          out << unify_string([str[1..-2]].pack('H*').force_encoding(Encoding::ASCII_8BIT))
        ##########################################
        ## parse a space delimited Hex String
        ##########################################
        elsif str = @scanner.scan(/<[0-9a-fA-F\s]*>/)
          # warn "Found a hex string"
          str = str.split(/\s/).map! {|b| b.length < 2 ? "0#{b}" : b}
          out << unify_string(str.pack('H*' * str.length).force_encoding(Encoding::ASCII_8BIT))
```

I'm uploading this version to Github, so you can practically download and test.

**Comment by emmanuelmillionaer** [comment]
Hello @boazsegev ! 🍾  🎉 

With your changes to the gem, I can now merge the PDF's easily. The text remains in the document! 👍  Will you release the changes as new gem-version? 🙂 

Thanks a lot for your efforts! Wish you a nice day ☀️

**Comment by boazsegev** [comment]
Hi @emmanuelmillionaer ,

I'm happy to help. Thank you for exposing this issue and testing the solution.

However, somewhere along my search for issue #107 , I broke an important piece of the code. When I manage to fix this (and hopefully fix the related issue along the way), I'll push a working version.

However, it might take me a few days (hopefully no more than that).

Kind regards,
   Bo.

**Comment by emmanuelmillionaer** [comment]
Hi @boazsegev , I hope you're doing well! 🙂 

Could you please tell me if the gem, is useable for the PDF's I described above?

Thanks for you help and this amazing Library! 🙂 

Greetings!

**Comment by boazsegev** [comment]
Hi @emmanuelmillionaer , Thanks for the `ping`... ☺️👍🏻

I'm well and I haven't forgotten. However, Lately the CombinePDF was failing tests in weird ways and it was very hard to track down the issue.

I'm now left with only two issues (maybe it's just one thing effecting two), where the tests for the Table Of Contents (TOC) fail... sometimes (I hate it when issues aren't persistent)... resulting in corrupted TOC titles. And the tests for the decryption fail consistently (even though I didn't touch the decrypt module)...

I hope to solve these last two shortly and than I'll release the updated version.

I admit, that even without fixing these issues, it's possible that the library will work better with the partial fixes, I'm just not sure if the decryption fails with the released version (I overwrote it on my computer by mistake 😂).

Anyway, feel free to nag, it helps when I feel a bit of pressure 👍🏻

Have an amazing day,
B.

**Comment by boazsegev** [comment]
@emmanuelmillionaer ,

I was about to give up for today and than I found the issue 👍🏻

I just released CombinePDF v. 1.0.0 🎉

Enjoy ☺️

**Comment by emmanuelmillionaer** [comment]
@boazsegev  That's awesome!  🥇  💯  🍾 

You are really a very committed and dedicated gem-maintainer, I want to express my Thanks for that 🙂 

Wish you a nice evening! 👍

**Comment by boazsegev** [comment]
@emmanuelmillionaer , You're very welcome 😊 and thank you for the positive feedback 🙏🏻
