### ISSUE TITLE
Stamp Location ?

### ISSUE THREAD

**Issue by DrakenZA** [boazsegev/combine_pdf#114]
Ive tried stamp_pages(foo,{:location => [:top]), nothing changed.
Ive tried stamp_pages(foo,{:x => 5 etc), nothing changed.

How can i adjust where the pdf gets combined at.

**Comment by boazsegev** [comment]
Is `foo` a String?

I'm asking because [the documentation says](http://www.rubydoc.info/gems/combine_pdf/1.0.3/CombinePDF%2FPDF:stamp_pages):

>  the stamp is a PDF page, only :page_range and :underlay (to reverse-stamp) are valid options

The reason is that managing stamp location for PDF data is a whole different game, both in of implementation and in user expectation...

**Comment by DrakenZA** [comment]
Foo is a PDF, the size of a logo, with a logo in it. As it stands, it ends up being placed bottom right. It might work for what i need, client might want it customable, hopefully not.

What would you suggest for taking a jpg and watermarking it onto a PDF.

Right now im taking the jpg, converting it to PDF, and combining it with the main PDF.

**Comment by boazsegev** [comment]
I'd love to help, but I need some information.

Are the images (the logo) dynamic?

Do you control the page size when you convert the image to PDF?

Are the PDF pages dynamic is size? And are the PDF pages consistent in size (or maybe each page could have a different size)?

These are all important factors in finding the best and fastest solution.

**Comment by DrakenZA** [comment]
Right now im simply using a free basic IMAGE to PDF online convertor. It results in a PDF, that is the same dimensions as the image.

Its simply for taking a single A4 PDF document, and watermarking it with the tiny PDF(dimensions are small)

**Comment by boazsegev** [comment]
Since you have control over both elements (all page sizes are A4 and the image PDF is pre-created), I think the fastest solution would be to make the image PDF in the A4 size, maybe convert the image to A4 and make sure it's placed exactly where you want it.

If this doesn't help you, let me know. The other options are more complex, some of them require a patch to the library, which might take more time.

**Comment by DrakenZA** [comment]
So i ended up using prawn and i did what you said. Created a document that is eqaul to the main one, and then i can just place the image with x,y.

Thank you pointing me in this direction.

**Comment by boazsegev** [comment]
@DrakenZA , 

You're welcome.

Your question indicated I might need to expose more of the internal working, to allow for dynamic adjustments to PDF stamps... however, I'm concerned about PDF internal workings being a bit weird (i.e., the XY axis starts at the bottom left).

I'm happy you found a good solution that can be applied offline, optimizing you application by reducing runtime code execution.

👍🏻
