### ISSUE TITLE
Ghostscript fails at parsing a generated pdf from combine_pdf 

### ISSUE THREAD

**Issue by albertsaave** [boazsegev/combine_pdf#116]
Hi,

I am creating a PDF using combine_pdf and then I use ghostscript to extract the images from it however I get the following error.

I tested with ghostscript version `9.06`. 

```
   **** Warning:  There are objects with matching object and generation
   **** numbers.  The accuracy of the resulting image is unknown.
%%BoundingBox: 50 152 544 812
%%HiResBoundingBox: 50.052163 152.747995 543.528968 811.655975
%%BoundingBox: 35 643 560 804
%%HiResBoundingBox: 35.621999 643.031980 559.000038 803.000015

   **** This file had errors that were repaired or ignored.
   **** The file was produced by:
   **** >>>> Ruby CombinePDF 1.0.0 Library <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```

Any help will be appreciated!

**Comment by boazsegev** [comment]
Hi @albertsaave ,

Thank you very much for opening this issue.

I would love to dig deeper into this, but I need an example PDF where this happens.

I know I fixed an issue where PDFs with Object Streams and multiple object versions were producing duplicate objects... but I thought I fixed that one... which version are you using?

Thanks!
   Bo.

**Comment by albertsaave** [comment]
Hi @boazsegev 

Here is a sample document: 
[doc-647-bcacd523dcc019e2ce1f96ab21e5303a.pdf](https://github.com/boazsegev/combine_pdf/files/1146500/doc-647-bcacd523dcc019e2ce1f96ab21e5303a.pdf)

And I was using using version 1.0.4 of combine_pdf.

**Comment by boazsegev** [comment]
@albertsaave 

Thanks a lot for the example!

I found that in some cases, root objects were written more than once (the exact same data, so there was no fear of data loss, but it was still an issue)...I have no idea why I didn't notice this before 🙄

I think I fixed the issue and I'll be releasing a patch in a few minutes.

However, if you find the issue persists please reopen the issue (or open a new one) and I'll look deeper.

Thank you very much for exposing the issue!

Bo.

**Comment by albertsaave** [comment]
Awesome! Thank you @boazsegev
