### ISSUE TITLE
Content get's lost when combining

### ISSUE THREAD

**Issue by emmanuelmillionaer** [boazsegev/combine_pdf#121]
Hi @boazsegev, 🙂  Thanks for this great Gem and the effort you put into it. 👏 
You achieved something impressive. 💯 🥇 

I really like to use it, but when I use this PDF the content get's lost. Can you please give me an advice/help me with it? 🙂 

[dimelo.pdf](https://github.com/boazsegev/combine_pdf/files/1194030/dimelo.pdf)

Wish you a great day! ☀️

**Comment by boazsegev** [comment]
Hi @emmanuelmillionaer ,

Thanks for opening this issue.

I can't seem to replicate the issue.

Can you give me more details or maybe a code example?

Is the data loss occurring when you combine the PDF with another PDF? 

Which version of CombinePDF are you using?

I tried opening the PDF and saving it as a new PDF using CombinePDF and I didn't notice any data loss.

Kindly,
   Bo.

**Comment by emmanuelmillionaer** [comment]
Hi @boazsegev thanks for your quick reply. 🙂 

After you told me that you were not able to replicate the issue, the last days I tried different file reading modes, and then it worked for me as well.

That's why I want to say thanks. 👍  Have an awesome day! 🙂  You did a great work with this Gem! 💯

**Comment by boazsegev** [comment]
Thanks for keeping me posted 👍🏻

I'm happy you found a solution and things are working out ☺️

Good luck with everything!
Bo.
