### ISSUE TITLE
Project Maintenance Inquiry

### ISSUE THREAD

**Issue by AdibMurshed** [boazsegev/combine_pdf#132]
Hello @boazsegev
On behalf of the Iniftar Foundations, I would like to claim this project to continue its development, open-source and non-profit.

**Comment by boazsegev** [comment]
Hi @AdibMurshed,

Thank you for your inquiry and welcome your offer!

However, I don't know you just yet and can't recall any contributions you may have made to this repository.

I would recommend that we take this idea step by step.

If you can help with any of the currently open issues, this would allow us to get to know each other and we can make sure this project is a good fit for you.

For now, please submit your changes as a PR and as things progress and we both see this as a good fit, I will add you as a maintainer etc'.

Kindly,
 Bo.

**Comment by AdibMurshed** [comment]
Hello @boazsegev ,

Once you transfer to the Iniftar Foundations, We have developers who will develop.

**Comment by boazsegev** [comment]
Hi @AdibMurshed ,

I understand your point of view. 

However, experience (and mostly [other people's experience](https://thefullstack.xyz/history-express-javascript-framework/)) shows that it's better to move slowly in these things.

I hope you understand my position and my concerns.

Kindly,
   Bo.

**Comment by AdibMurshed** [comment]
Hi @boazegev <https://github.com/boazegev>,

I understand what you mean. In my experience, it's the same, there is a lot
of concern these days on the internet.

I also agree to take these things slowly but steadily (just like the
tortoise and the hare story). But more than just quickly doing whatever
with pull requests, I suggest we take this by talk and trust. You may like
to learn more about the organization I would like to assign this project
to, http://www.blog.iniftar.com.

Kind Regards with all the best,
Adib.

**Comment by jpmcgrath** [comment]
https://github.com/python-mode/python-mode/issues/804

**Comment by ms-ati** [comment]
@jpmcgrath Kudos on your welcoming and wise responses here. In the interests of protecting the wider world against what may be an emerging threat model, is there anything more that can be done to highlight this case for further investigation and/or publicization?

**Comment by AdibMurshed** [comment]
@ms-ati No idea who you are but for your information, this was not with negative intentions and was dealt with a year ago to the extent between GitHub support and myself. There is no threat in kindly offering to claim open-source projects with a good intention and in the fear of it being discontinued to the distress of developers. I agree with @jpmcgrath that it is almost impossible to trust someone with no previous history with the project and that's why I silenced myself here on GitHub. Thank you.

**Comment by boazsegev** [comment]
@AdibMurshed ,

I want to point out that I was happy to read your offer.

I didn't believe you have any bad intentions and I still don't think you have bad intentions. I just didn't have any way to make sure you were the best fit.

However, @ms-ati makes a good point. Some people, not you, do take over open source projects and run them aground.

A good (and sad) example might be [the node.js express framework experience](https://thefullstack.xyz/history-express-javascript-framework), which was a cause for much distress for those of us that were following along.

I believe @ms-ati 's comment wasn't meant as a personal attack, but a reflection of his/her desire to raise awareness regarding these risks.

Happy New Year 🎉,
  Bo.

**Comment by AdibMurshed** [comment]
@boazsegev Thank you for the kind response. It is very unfortunate to see the ones with bad intentions and without doubt I support his/her desire to raise awareness regarding these risks. 

I guess I have someone to blame for ruining the image of many organizations and companies who wish to preserve and protect open-source projects :)

Happy New Year 🎉.
Adib.
