### ISSUE TITLE
PDF parsing error from producer Aspose.Words for Java 16.10.0.0

### ISSUE THREAD

**Issue by Defoncesko** [boazsegev/combine_pdf#141]
Hi !
First of all, thanks a lot for your amazing gem !

I'm currently facing problems while parsing one PDF using combine_pdf (v1.0.12) : 
`Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>24, :referenced_object=>nil}`
`Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>23, :referenced_object=>nil}`
`Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>93, :referenced_object=>nil}`
`Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>92, :referenced_object=>nil}`
`Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>93, :referenced_object=>nil}`

Here is the input PDF : 
> https://drive.google.com/file/d/1BNMsUXmpcaIgeZqYkHgB6k0ueU-UEo80

Here is my code : 
`CombinePDF.parse( Net::HTTP.get( URI.parse( d.page.url ) ) )`
The output PDF is blank using Firefox, but using Chrome some caracters are not displayed well.

**Comment by boazsegev** [comment]
Hi @Defoncesko ,

Thank you for opening and exposing this issue 🙏🏻🙏🏻🙏🏻

I authored a possible fix.

Is there any chance you could test this issue with version 1.0.13 (just released)?

Kindly,
  Bo.

**Comment by Defoncesko** [comment]
Hi !
Just tested with new version 1.0.13.
It works fine, problem solved !

Thanks a lot !
