### ISSUE TITLE
Possible to show total number of pages with number_pages method?

### ISSUE THREAD

**Issue by leesmith** [boazsegev/combine_pdf#144]
Is it possible to show "3 of 8" as an optional format to the `number_pages` method? Thanks!

**Comment by boazsegev** [comment]
Hi @leesmith 

Sure it's possible. Read the documentation for [`CombinePDF::PDF#number_pages`](https://www.rubydoc.info/gems/combine_pdf/1.0.15/CombinePDF/PDF#number_pages-instance_method) and consider:

```ruby
filename = "foo.pdf"
pdf = CombinePDF.load filename
page_count = pdf.pages.length
number_format = "%s of #{page_count}"
pdf.number_pages number_format: number_format
```

Kindly,
   Bo.

**Comment by leesmith** [comment]
That worked perfectly! Thanks @boazsegev 🍻
