### ISSUE TITLE
Add content to existing pages (Stamp / Watermark) not working with pdf created by Mac Pages

### ISSUE THREAD

**Issue by SubhaPrince** [boazsegev/combine_pdf#146]
To add content to existing PDF pages, 
first I imported the new template content from an existing PDF file created by **Mac pages/google doc.** 
after that, added the content to each of the pages in your existing PDF where only template content is showing the content text not **showing** because **font color of the content text is white**

however template PDF created by Microsoft Office is working perfectly..
**Please tell me why this is not working for PDF created by google doc or mac pages**

Thanks

**Comment by boazsegev** [comment]
Hi @SubhaPrince ,

Thank you for opening these issues.

Without access to the template files themselves I cannot answer you.

My guess is that the PDF you're attaching has a white background layer (it isn't transparent).

This seems to be related to issue #145 ... so we can continue the discussion there.

Kindly,
   Bo.
