### ISSUE TITLE
Latin chars stamp_pages not working

### ISSUE THREAD

**Issue by RBN1993** [boazsegev/combine_pdf#153]
Hi everyone,
I tried to print this string _'Campa**ñ**a_ ' or this other _'P**í**o_' and i obtain this **'Campaˆ–a**' and **'Pˆ›o**' with **stamp_pages()** . How can i fix this problem?. 
Thak you.

**Comment by boazsegev** [comment]
Hi @RBN1993 ,

Thank you for opening this issue.

This is a known limitation of the PDF standard, nothing I can do about it in ComBinePDF - PDFs only support ASCI text, as [mentioned in the documentation](https://www.rubydoc.info/gems/combine_pdf/1.0.15/CombinePDF/PDF#fonts-instance_method).

The best approach to using UTF-8 / latin fonts, is to import a font from an existing PDF using [the `PDF#fonts` method](https://www.rubydoc.info/gems/combine_pdf/1.0.15/CombinePDF/PDF#fonts-instance_method).

There's a discussion about it in [this issue](https://github.com/boazsegev/combine_pdf/issues/137).

Good luck.
    Bo.

P.S.

If you feel that the documentation wasn't clear about this or that the information wasn't repeated enough in the right places, please submit a PR.

Thanks!
   B.
