### ISSUE TITLE
Can't able to use rails 5.0.1

### ISSUE THREAD

**Issue by prasanthrubyist** [boazsegev/combine_pdf#154]
if I bundle update, It's working fine, I can't able to use existing version, Help me
```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.1, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails (>= 5.0.0.1, ~> 5.0.0)', in any of the sources.

```

**Comment by boazsegev** [comment]
Hi @paulslaby 

I'm not sure I understand the issue. The gem should be usable with any Rails version, it requires bundler >= 1.7 which fits inside the specified range (1.3 <= version < 2.0).

Can you post your gem file and the code you use to produce this error?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Did you try starting rails using `bundler exec`? i.e.

```bash
bundler exec rails s
```

Or (with iodine):
```bash
bundler exec iodine -t 1
```

**Comment by boazsegev** [comment]
Closed due to inactivity.
