### ISSUE TITLE
[Tiny issue] api.rb shows a harmless "mismatched indentation" warning

### ISSUE THREAD

**Issue by rubyFeedback** [boazsegev/combine_pdf#173]
Hello boazsegev,

Not sure if such small warnings should be filed as an issue, sorry.  :) 

But the good thing is that these are easy to correct.

Warning is this for me:

     /usr/lib/ruby/gems/2.7.0/gems/combine_pdf-1.0.18/lib/combine_pdf/api.rb:31: warning: mismatched indentations at 'rescue' with 'begin' at 25

I think the indent just has to be shuffled a bit to the right, for that warning
to disappear. (I think a single begin/rescue clause may suffice by the way;
nested begin/rescues are a bit harder to read, but that is aside from this
issue request - this one is solely about the warning. I noticed it because
I tend to run my .rb files with -w flag all the time).

**Comment by boazsegev** [comment]
Hi @rubyFeedback,

Thank you for opening this issue. I pushed a commit to fix this. It will be fixed with the next release.

Kindly,
  Bo.
