### ISSUE TITLE
[Documentation] Small suggestion (copy/paste-able)

### ISSUE THREAD

**Issue by rubyFeedback** [boazsegev/combine_pdf#174]
Hello boazsegev,

Sorry to bother you again. :)

The main README has this documentation right now at page number:

"Numbering can be done with many different options, with different formating, with or without a box object, and even with opacity values - see documentation."

I suggest to append these examples:

"If you would like to place the page number on the bottom right side of all .pdf pages, do:"

    pdf.number_pages(location: :bottom_right)

and:

"If you wish to increase the font size as well, you could use this:"

    pdf.number_pages(location: :bottom_right, font_size: 44)

I found these examples when reading the comments in the .rb file. :)
Perhaps someone else may find this useful too, hence why I added this
small issue request.

**Comment by boazsegev** [comment]
Hi @rubyFeedback ,

Thank you for opening this issue!

I'll definitely add some examples 👍🏻

Cheers!
   Bo.
