### ISSUE TITLE
Russian language font

### ISSUE THREAD

**Issue by 5anchezzz** [boazsegev/combine_pdf#179]
Hello! I have a problem with displaying a Russian language font.
When I try to import a font from an existing PDF using the PDF#fonts method, i get empty array.
`fonts = CombinePDF.new("/Users/sanchez/decart/send-pdf/certificates-2/main-fix.pdf").fonts(true)`
` => [] `
As far as I understand, the font in the pdf file is loaded and has type 0.
![image](https://user-images.githubusercontent.com/49248922/96856641-cdfc0f00-1466-11eb-9aac-0bfbb8735e63.png)

![image](https://user-images.githubusercontent.com/49248922/96856752-f257eb80-1466-11eb-892c-0699c061e385.png)

Here is the file with the desired font
[main-fix.pdf](https://github.com/boazsegev/combine_pdf/files/5422131/main-fix.pdf)

What am I doing wrong?

**UPDATE:**
I was able to create a pdf file that gives Montserrat font on `fonts = CombinePDF.new("montserrat_font.pdf").fonts(true)`
[montserrat_font.pdf](https://github.com/boazsegev/combine_pdf/files/5423252/montserrat_font.pdf)

But that also didn't solve the problem.
After importing the font with `CombinePDF.register_font_from_pdf_object :montserrat, fonts[0]` it appears in the list of available:
`2.6.5 :049 > CombinePDF::Fonts.fonts_list()`
 `=> [:"Times-Roman", :"Times-Bold", :"Times-Italic", :"Times-BoldItalic", :Helvetica, :"Helvetica-Bold", :"Helvetica-BoldOblique", :"Helvetica-Oblique", :Courier, :"Courier-Bold", :"Courier-Oblique", :"Courier-BoldOblique", :Symbol, :ZapfDingbats, :montserrat ]  `

but when creating a textbox and explicitly setting the font, nothing appears in the pdf file.

It is very upsetting when you think that the problem is almost solved, but in fact nothing has changed)

**Comment by boazsegev** [comment]
Привет @5anchezzz ,

I noticed, when I run `CombinePDF::Fonts.get_font(:montserrat).cmap`, that I get:

```ruby
CombinePDF::Fonts.get_font(:montserrat).cmap
# => {" "=>"20", "П"=>"21", "р"=>"22", "и"=>"23", "в"=>"24", "е"=>"25", "т"=>"26"}
```

This shows that the font only contains a small subset of the Russian alphabet. You might want to create a PDF file that has all the russian letters (preferably in order)... `"абсдеф...АБСДЕФ..."`.

Then you will be able to use all the letters that the font provides - assuming your input has the same encoring as the letters in the `cmap`.

Good Luck - Удачи!
   Bo.

**Comment by 5anchezzz** [comment]
Hello, @boazsegev ! Thank you very much for your reply!
I created a pdf-file containing all the letters of the alphabet
[font-montserrat.pdf](https://github.com/boazsegev/combine_pdf/files/5428503/font-montserrat.pdf)

and checked it your way. But this font cannot be passed to parameters when creating a textbox.
![image](https://user-images.githubusercontent.com/49248922/96986354-33650400-152a-11eb-87de-19bccc370e34.png)

code example
```ruby
  def combine_cert
    cert_folder_path = "/Users/sanchez/decart/send-pdf/combine/certs/#{email}"
    FileUtils.mkdir_p(cert_folder_path) unless File.exist?(cert_folder_path)

    fonts = CombinePDF.new("/Users/sanchez/decart/send-pdf/combine/template/font-montserrat.pdf").fonts(true)
    CombinePDF.register_font_from_pdf_object :montserrat, fonts[0]

    pdf = CombinePDF.load "/Users/sanchez/decart/send-pdf/combine/template/main.pdf"
    pdf.pages[0].textbox("РУССКИЙ", { font: :montserrat })
    pdf.save "/Users/sanchez/decart/send-pdf/combine/certs/#{email}/main.pdf"
  end
```

**Comment by boazsegev** [comment]
There was an issue where the font doesn't publish the glyph's dimension properly.

I patched CombinePDF with a workaround the issue.

Please update to version 1.0.19.

I'm attaching [the result for my attempt](https://github.com/boazsegev/combine_pdf/files/5429050/1.pdf).

Good luck!

**Comment by boazsegev** [comment]
@5anchezzz  - could you please let me know if 1.0.19 solved your problem? Can I close this issue?

**Comment by 5anchezzz** [comment]
Awesome! Everything worked out! @boazsegev , thank you very much for your help! Great gem!

**Comment by boazsegev** [comment]
Thanks 🎉
