### ISSUE TITLE
get PDF original metadata

### ISSUE THREAD

**Issue by MathieuDerelle** [boazsegev/combine_pdf#181]
Is there a way to get the original metadata of a PDF we are opening with your gem

This line is overwritting  directly `Producer`

https://github.com/boazsegev/combine_pdf/blob/3226cf18b1832f942d7fe904a0fd40eefd7a4f31/lib/combine_pdf/pdf_public.rb#L112

Could you expose the original metadata as `original_info` or expose [`parser`](https://github.com/boazsegev/combine_pdf/blob/3226cf18b1832f942d7fe904a0fd40eefd7a4f31/lib/combine_pdf/pdf_public.rb#L96) maybe ?

**Comment by boazsegev** [comment]
Hi @MathieuDerelle ,

You could always use the `CombinePDF::Parser` class manually before creating a new `CombinePDF::PDF` object, allowing you to extract the information before it's overwritten.

As a quick sketch (untested):

```ruby
parser =  PDFParser.new(IO.read(file_name, mode: 'rb').force_encoding(Encoding::ASCII_8BIT))
info = parser.info_object.dup
pdf = PDF.new(parser)
puts info[:Producer] # => should contain original producer value
```

However, the producer **should** be updated if you save the PDF using CombinePDF. This makes it easier to track issues with PDF formatting.

Good luck!
   Bo.
