### ISSUE TITLE
metrics for x/y coordinates 

### ISSUE THREAD

**Issue by RailsCod3rFuture** [boazsegev/combine_pdf#187]
Hello, I am using GIMP for finding the coordinates on my pdf fields. Oddly, they're off by a large margin. Do you have a method or approach that gives you the exact position of a form element on the pdf?

**Comment by boazsegev** [comment]
Hi @RailsCod3rFuture ,

Thank you for opening this issue.

Just to make sure - are you aware that PDF XY coordinates start at the **bottom** left of the page and build **up** (unlike most graphical applications that list coordinates from the **top** left, building down)...?

Kindly,
   Bo.

**Comment by RailsCod3rFuture** [comment]
Alright. Thanks.
