### ISSUE TITLE
Special symbols in metadata

### ISSUE THREAD

**Issue by d-kononov** [boazsegev/combine_pdf#188]
Hello!

Is it possible to use special symbols in metadata? I tried to set producer = `Fingerspitzengefühl` and got: 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1768345/107481854-0d32a500-6ba9-11eb-9d13-043f3605fb4f.png">
I used `get info` option of the file, but `pdfinfo` (command line tool) shows correct info.

**Comment by boazsegev** [comment]
Hi @d-kononov ,

Thank you for your question. This might be related to #192 , which might answer your question.

As stated over there:

> The PDF specifications don't support UTF-8. Multi-lingual documents are handled by using Fong mappings where ANSI letters are mapped to the international glyph.
> 
> However, the title information has no font and no mapping, so I think reader software reads the title string as ANSI letters (maybe adding a UTF-8 BOM will fix that, but I'm not remotely sure) ...
> 
> ... anyway, [this was the case before PDF 2.0](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf). I have no idea how [the new standard](https://www.iso.org/standard/75839.html) looks like because it isn't available for free.
> 
> I have no idea how to change that.

Kindly,
   Boaz Segev.

**Comment by conorom** [comment]
I realize this issue is closed but I ran into the same thing and solved it by encoding the string as UTF-16:
`pdf.to_pdf({ producer: producer.encode('utf-16') })`

The value then shows up correctly in exiftool and Acrobat file properties.
https://tex.stackexchange.com/a/245969
https://stackoverflow.com/a/3063966
