### ISSUE TITLE
Some PDF pages cannot be injected with text objects

### ISSUE THREAD

**Issue by boazsegev** [boazsegev/combine_pdf#2]
Some PDFs, specifically certain scanned PDF files (usually those with text recognition), cannot be injected with text objects.

The text injected into those PDF pages (I tried numbering the pages) was not rendered - or, as far as I could tell, was rendered as transparent (render mode 3) even when the mode operator (render modes 1 and 2) was present.

Shapes injected into the same pages were rendered correctly.

Seems as if the previous content streams (the ones after which the content is injected) override the later content streams (the injected data).

Reversing the streams order could not be tested, because the white page - although scanned - isn't transparent, so that the content "behind" it could not be observed.

**Comment by donnguyen** [comment]
Hi @boazsegev 
I am not sure the issue we are facing here is related to this but can you please take a look at these PDF files:
[verified_vit_card_pdf_carla_gangi.pdf](https://github.com/boazsegev/combine_pdf/files/963468/verified_vit_card_pdf_carla_gangi.pdf)
[verified_First_Aid_Certificate_2016.pdf](https://github.com/boazsegev/combine_pdf/files/963469/verified_First_Aid_Certificate_2016.pdf)
We are trying to add some `textbox` to these PDF files but it just doesn't work (without any error messages and the same code work with other files).

Thanks

**Comment by boazsegev** [comment]
Hi Đôn Nguyễn,

Thank you for opening this issue :-)

I tried opening the files and writing text, but it seemed to have worked on my machine... maybe it's something I'm doing different...? or a different version...?

Which version are you using?

Can you please post an example code that demonstrates the issue?

I'm very busy these next two weeks because these are the last two weeks of this semester at my collage, but I hope I will be able to get a look soon and help you solve the issue.

Thanks again,
Bo.

**Comment by boazsegev** [comment]
@donnguyen

Please let me know if you still experience the issue.

Kindly,
Bo.

**Comment by donnguyen** [comment]
hi @boazsegev 
Thanks for your help! And actually it works fine my side now also. Maybe I used it the wrong way, just changed a single code line, and it works perfectly. But I still couldn't figure out why it happened with some files only.

Again, thank you, @boazsegev 👍

**Comment by donnguyen** [comment]
Btw, below is the code that we used:
```ruby
    watermark = "Text here"
    pdf.pages.each do |page|
      page.textbox "", opacity: 0.7, height: 40, y: 810,
                   box_color: [1,1,1]
      page.textbox watermark, text_valign: :top,
                   font_size: 8, font_color: [0,0,0], height: 15, y: 822,
                   text_align: :center
      page.textbox "Text here again", text_valign: :top,
                   font_size: 8, font_color: [0,0,0], height: 15, y: 812,
                   text_align: :center
    end
```

And here is the working code:
```ruby
    watermark = "Text here"
    pdf.pages.each do |page|
      v_position = page.page_size[3]
      page.textbox "", opacity: 0.7, height: 40, y: v_position - 28,
                   box_color: [1,1,1]
      page.textbox watermark,
                   font_size: 8, text_valign: :top, y: v_position - 50
      page.textbox "Text here again",
                   font_size: 8, text_valign: :top, y: v_position - 250
    end
```

**Comment by boazsegev** [comment]
Hi @donnguyen ,

Thanks for keeping me posted!

I think the reason might be that not all PDF files start at Y=0... but the default `:y` value for the `textbook` is 0.

I think I'll change the default on the next release, to allow for non-zero / cropped page origin points (i.e., pages that start at 10,10).

Thanks again and good luck,
   Bo.
