### ISSUE TITLE
root is unknown - cannot determine if file is Encrypted - only in production

### ISSUE THREAD

**Issue by francescob** [boazsegev/combine_pdf#24]
Hello, i'm having some problems reading a pdf, the error is the one reported in the subject, the strange things is that it works just great in development, but in production i get this strange error. Also reading the file from console works correctly, both in dev or production enviroments

**Comment by francescob** [comment]
Sorry problem was caused by me trying to iper the file with wrong case and it was working in dev mode because of a case insensitive file system

**Comment by boazsegev** [comment]
Yeah, I need to update the error message so it's clearer that a 'file not found' is also possible.

Thanks.
