### ISSUE TITLE
"FrozenError: can't modify frozen String" in 2.7 with frozen string literal options

### ISSUE THREAD

**Issue by anthonykaufman** [boazsegev/combine_pdf#243]
In the latest gem (1.0.27) I'm getting "FrozenError: can't modify frozen String" in several places in the `combine_pdf/renderer`. Though I originally encountered this in Ruby 2.5, I can reproduce in 2.7 using the `--enable-frozen-string-literal` and `--debug-frozen-string-literal` flags.

I've created some tests which expose and fixed by adding `.b` to a few literals. I can submit as a PR if that'd be helpful.

**Comment by boazsegev** [comment]
Hi @anthonykaufman ,

I tried reproducing this issue, but as my Ruby version is on 3+, I can't seem to replicate this.

Can you please provide a PR, or a backtrace, to allow me to dig deeper?

Thanks!

**Comment by anthonykaufman** [comment]
Sorry, for the slow reply here. Got a little sidetracked with other projects last week. Here's that PR including steps to reproduce:
https://github.com/boazsegev/combine_pdf/pull/244

**Comment by francescob** [comment]
I'm seeing this in ruby 3.3.4 also:

`10:05:23 rails.1       | FrozenError - can't modify frozen String: "":
10:05:23 rails.1       |    () home/francesco/.asdf/installs/ruby/3.3.4/lib64/ruby/gems/3.3.0/bundler/gems/combine_pdf-44f46faae788/lib/combine_pdf/page_methods.rb:289:in `textbox'`

**Comment by boazsegev** [comment]
Fixed in 1.0.29
