### ISSUE TITLE
File parsing fail when the `endobj` keyword is missing

### ISSUE THREAD

**Issue by ancv1990** [boazsegev/combine_pdf#27]
Hi @boazsegev,

Sometimes I got this error when combine two pdf file:
no implicit conversion of Symbol into Integer
  .../ruby/2.0.0/gems/combine_pdf-0.1.16/lib/combine_pdf/combine_pdf_pdf.rb:582:in `[]'

Please help me solve it.

**Comment by boazsegev** [comment]
Thank you for contacting me with this issue.

I'm traveling at the moment. It will probably take me 10 days before I can get a look at it.

Could you send sample PDF files, so I could test this out?

**Comment by boazsegev** [comment]
P.S.

I noticed this issue is related to version 0.1.16.

The current version is 0.2.4.

Could you update and test again?

**Comment by ancv1990** [comment]
Got it @boazsegev, I will update version and test again.
Thanks.

**Comment by boazsegev** [comment]
Please let me know if the issue had resolved. I would be very happy to fix it if we need to.

Tomorrow I'll go to the desert for 5 days and I'm leaving my laptop here... so if the issue persists, it might take me a bit before I can fix it. But I will try my best.

**Comment by ancv1990** [comment]
That problem just appears rarely. So it may take long time to know if problem had solved.
I will let you if problem still happen.
Thanks @boazsegev for great support.

**Comment by ancv1990** [comment]
Hi @boazsegev, after upgrade to version 0.2.4, I got new error:
General PDF error - Use CombinePDF.load or CombinePDF.parse for a non-general error message (the requested file was not found OR the string received is not a valid PDF stream OR the file was found but not valid).

Please check it.
Thanks

**Comment by boazsegev** [comment]
@ancv1990 , This error message is raised during normal operation when a non-PDF file parsing is attempted.

This could be an issue if the file IS a correctly authored PDF file, but I will need a file that doesn't open to debug this issue.

Can you send me a file to my email or post a link to the PDF file in question?

**Comment by ancv1990** [comment]
Hi @boazsegev, what's your email?
I will send you the pdf file.

Thanks

**Comment by boazsegev** [comment]
boaz@2be.co.il

**Comment by boazsegev** [comment]
Please test with version 0.2.5 and keep me posted.

Thanks for helping to make CombinePDF better.

**Comment by ancv1990** [comment]
Ok @boazsegev, I will test and let you know if it works.

Thanks for your quick fixing.
