### ISSUE TITLE
Clarify error optional content

### ISSUE THREAD

**Issue by cw6365** [boazsegev/combine_pdf#28]
i get the following runtime error "Optional Content PDF files aren't supported and their pages cannot be safely extracted", this is a one off error and doesn't normally happen so looks to be pdf specific.

I've had a look at the code but can you quickly clarify the issue here for me please. Thanks.

**Comment by boazsegev** [comment]
Some PDF files are designed to display different content according to the media on which they are displayed.

For example, a PDF file might display one way when viewed on screen and it might replace some images or text when printed on paper... Just like some websites use the CSS media query.

These PDF file required very specific instructions inside their structure. Ignoring these instructions might produce corrupted files or files that look very different than what you wanted them to look like.

Because of the issues related with this structure, these files are not supported for now and cannot be merged with other PDF files.

**Comment by andyrue** [comment]
What's the best way to catch this error?

**Comment by andyrue** [comment]
What's the best way to rescue from this error? I tried wrapping my `CombinePDF.load` command in a `begin, rescue` but it hangs upon running.

**Comment by boazsegev** [comment]
@andyrue , could you post your code you tried?

The following should work (I think, I don't have a file to test with):

```ruby
filename  = 'file.pdf'
begin
   pdf = CombinePDF.load filename
rescue => e
   puts "Couldn't load #{filename}: #{e.message}"
end
```

**Comment by andyrue** [comment]
Seems there was some ruby process stuck. I killed it with activity monitor and the `begin` `rescue` works now. Thanks for your quick response!

**Comment by joelw** [comment]
Would you support a PR to add an option to ignore this error? For my use case I'd be happier with potentially weird output than no output at all, and when I've tested commenting out the `raise` my test PDFs look just terrific!

**Comment by boazsegev** [comment]
Hi Joel,

Thanks for asking.

If the PR allowed this as a non-default option, yeah sure.

I think it's better if the default would fail then to risk quite failures (missing data), but I definitely understand that different implementations might prefer a different behavior.

P.S.

If you're writing in a option flag to the existing API (i.e. `CombinePDF.load file_name, unsafe: true`), it might be better to use a hash then a simple argument, allowing for future features and alterations.

**Comment by joelw** [comment]
Thanks for your quick response (and for the gem!) I've put something together and will create a PR :)

**Comment by chrisconcepcion** [comment]
Ran into this issue and found an odd solution using the libreconv gem. Essentially you convert the pdf to a pdf with libreoffice and this will make the pdf compatible with combinepdf. Hope this helps someone, took me hours to figure this out.

Libreconv.convert(document_path, document_path)

**Comment by caioagiani** [comment]
Try this:

```ruby
CombinePDF.load("your_file.pdf", unsafe: true, allow_optional_content: true)
```
