### ISSUE TITLE
Output file cannot be saved from Adobe Reader with "Save As optimizes for Fast Web View" preference enabled.

### ISSUE THREAD

**Issue by hasaniskandar** [boazsegev/combine_pdf#30]
Getting error "The document could not be saved. There was a problem reading this document (23)." while trying to save the output file from Adobe Reader with "Save As optimizes for Fast Web View" preference enabled.

**Comment by hasaniskandar** [comment]
Submitted PR #29 to fix this.

**Comment by boazsegev** [comment]
💙💚💛Nice work!💛💚💙

Thanks for discovering the issue and writing the code to resolve it.
