### ISSUE TITLE
Latest release breaks page cominations

### ISSUE THREAD

**Issue by davekrupinski** [boazsegev/combine_pdf#35]
After upgraded to Nov 4th release, I now receive this error:

"no implicit conversion of Symbol into Integer"

Here is a portion of the backtrace:

```
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:616:in `[]'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:616:in `init_contents'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:601:in `block in copy'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:601:in `instance_exec'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:601:in `copy'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:58:in `inject_page'
combine_pdf (0.2.10) lib/combine_pdf/page_methods.rb:49:in `<<'
```

**Comment by boazsegev** [comment]
Hi Dave, thank you for posting this issue 🙏🏻

I'm super sorry about this. I usually manually test with a bunch of PDF files, but it was such a minor fix and it seemed... I guess I was foolish.

Anyway, should be working with version 0.2.11 - please check it out and let me know?
