### ISSUE TITLE
Open and save sign pdf

### ISSUE THREAD

**Issue by nepturial** [boazsegev/combine_pdf#38]
I need to stamp a logo in a file signed, but when I use

pdf = CombinePDF.load "signed_document.pdf"
pdf.save "signed_stamped_document.pdf"

the signature was deleted

so...this gem support or will support files signed?

**Comment by boazsegev** [comment]
Signatures are often used to show that a PDF wasn't "tampered" with. i.e. that pages weren't added nor removed, that content hadn't changed etc'.

When you stamp a signed PDF, the signature is no longer valid and you need to re-sign the PDF.

At the moment, combine_pdf doesn't sign PDF files. I hope that in the future this feature can be added... but I'm working alone on this project and unless I get some help than it will be a while before I can get to work on the more complicated features I want to add (such as outlines, PDF signing and optional content PDF handling).

**Comment by nepturial** [comment]
Dont want sign PDF, only manipulate the file without lose the signature.
This issue was for know if I am doing the wrong things.
I will going to use itext for my purpose or something like this

Thx anyway and good luck!

**Comment by boazsegev** [comment]
Good luck.

For your information, The signature is written to the PDF after all the PDF was rendered to a byte stream and the byte stream is hashed as part of the signature.

(first the file is created and NULL bytes are used where the signature will be placed, after the signature process hashes the files, the signature is written over the NULL byes)

This means that signatures aren't valid if **any** bytes are added or removed from the PDF file.

It could be that iText will give you something that CombinePDF doesn't... but even if iText keeps the signature, you might get odd results from the PDF readers. The signature will be checked against the bytes in the file and the error will be raised by the PDF reader (each reader might handle the error differently, by either displaying a warning message or even refusing to open the file).
