### ISSUE TITLE
Check for corrupt pdf file

### ISSUE THREAD

**Issue by Subtletree** [boazsegev/combine_pdf#40]
Firstly thanks for the awesome gem!

I have a pdf that returns this error `Unknown PDF parsing error - maleformed PDF file?` when parsing.

Is it possible to check if a pdf is corrupt and not parse it if that is the case, so not to break the whole request?

I'm using version 0.2.14. The pdf in question is version 1.2.

Cheers!

**Comment by boazsegev** [comment]
I think the simplest solution would be to wrap the code within a `begin`...`rescue` block...

The following example was part of the answer for issue #28 :

```ruby
filename  = 'file.pdf'
begin
   pdf = CombinePDF.load filename
rescue => e
   puts "Couldn't load #{filename}: #{e.message}"
end
```

You can look at [the code for the demo app](https://github.com/boazsegev/combine_pdf_demo/blob/996e3f145b72fa31bc831b441f0cf42021c5e509/pdf_controller.rb#L323-L329) to see how I used a rescue block to redirect an Http response and display an error message (I used the Plezi framework, but Rails would be similar).

**Comment by boazsegev** [comment]
And Ryan, Thank you for asking. I'm happy to help and I'm pleased to read that you're enjoying my library :-)

**Comment by boazsegev** [comment]
P.S.

If it's possible to read the PDF file in a PDF reader, I would appreciate a copy of the file, so I could fix the actual issue (the file not being parsed).

Thanks!

**Comment by Subtletree** [comment]
Thanks for the help! Using rescue is working well.

I have emailed you the pdf file.
