### ISSUE TITLE
Issues with Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by andymilk** [boazsegev/combine_pdf#43]
When I open a PDF generated by combine_pdf in Adobe Acrobat Reader DC, there are a couple issues:

If I add a Sticky Note to it and save the file, the Sticky Note shows on every page of the PDF.

On a PC, I get an error from Acrobat: "The document could not be saved. There was a problem reading this document. (23)"

Has anyone else come across this? 

Thanks

**Comment by boazsegev** [comment]
Hmmm...

I tested with Acrobat Reader on mac:
Architecture: x86_64
Build: 15.10.20056.167417
AGM: 4.30.61
CoolType: 5.14.5
JP2K: 1.2.2.35592

I couldn't reproduce the issue... Anyone?

**Comment by boazsegev** [comment]
I'm closing the issue, as I can't reproduce the issue and it's gone stale.

If the issue persists, please reopen the issue and provide any new data you have.

Thank you.
