### ISSUE TITLE
Can i use Combine PDF to only replace links location?

### ISSUE THREAD

**Issue by crysper** [boazsegev/combine_pdf#46]
Hey,

I'm looking for days for a solution and couldn't find it. I know you can stamp, merge 2 pdf, but is there a way that I can only the links addresses of the document?

Visually the document should be the same, just the links should be different.

Thanks a lot

**Comment by boazsegev** [comment]
Hmmm... Well, I guess the answer would be "No", even though CombinePDF allows you to take apart the PDF and inject new data inside (as well as changing the links, I guess)... but this would require more knowledge of the PDF structure and CombinePDF doesn't provide a comfortable API to do so.

Good luck finding a library or hacking your way towards a solution.
