### ISSUE TITLE
Page number overlays table content

### ISSUE THREAD

**Issue by lhumungus** [boazsegev/combine_pdf#48]
Thanks for writing this awesome gem!  When I add page numbers to my PDF, say at the bottom, it overlays whatever content may already exist there.  How can I adjust the page number so it displays at a certain position in the margin/footer/header?

Thanks for your help.

**Comment by boazsegev** [comment]
Hi @lhumungus,

The [page numbering method](http://www.rubydoc.info/gems/combine_pdf/0.2.15/CombinePDF%2FPDF%3Anumber_pages) actually applies the [Page#textbox method](http://www.rubydoc.info/gems/combine_pdf/0.2.15/CombinePDF%2FPage_Methods%3Atextbox), and has some options that you can use (you can read the documentation for all the options).

You can set the location, font size, color, text box background (border, colors and corner radius), opacity and many other features.

You can use a specific position using the `:x` and `:y` options, or use helpers such as the margin settings - they're specified in the [PDF#number_pages method documentation](http://www.rubydoc.info/gems/combine_pdf/0.2.15/CombinePDF%2FPDF%3Anumber_pages). i.e.:

```ruby
pdf.number_pages number_format: " - Draft, page %d - ",
    number_location: [:top],
    margin_from_height: 100,
    font_color: [0,0,1],
    box_color: [0.4,0,0],
    opacity: 0.75,
    box_radius: 8
    font_size:16

```

Good luck!
Bo.
