### ISSUE TITLE
won't be able to load Adobe LiveCycle pdf file

### ISSUE THREAD

**Issue by vsrboth** [boazsegev/combine_pdf#57]
hi @boazsegev 

It seems the library is having an issue loading pdf file that is creating using Adobe LiveCycle (containing xml file).

[Link to download sample pdf](https://drive.google.com/file/d/0B3XxI5-WHNbLNWFwZ3psVXljems/view?usp=sharing)

here is the error I got

<img width="1421" alt="screen shot 2016-05-01 at 9 58 19 am" src="https://cloud.githubusercontent.com/assets/5484995/14939862/c9f5ebd8-0f84-11e6-84b5-e52b8b3dd44d.png">

**Comment by boazsegev** [comment]
Hi @vsrboth ,

Thank you for reporting the issue.

Could you please explain what you're experiencing?

I downloaded the file to test and `CombinePDF.load` loaded the file properly.

The warnings are due to the fact that some features aren't fully supported by the library, so the library is warning about potential data loss... but I didn't notice any data loss, did you?

Best regards,
   Bo.

**Comment by vsrboth** [comment]
Hi @boazsegev ,

thank you so much for your prompt assistance (so much appreciate [bow]). 

Problem is it takes me forever to load the pdf file. Probably you can find another [Pdf sample](https://drive.google.com/file/d/0B3XxI5-WHNbLcDRzRXNxT0NPTDQ/view?usp=sharing) for testing.

<img width="1425" alt="screen shot 2016-05-01 at 2 45 09 pm" src="https://cloud.githubusercontent.com/assets/5484995/14940705/5e1726b2-0fab-11e6-9fb6-0a7c639c3dda.png">


Note: I am using Mac - El Captian.

**Comment by boazsegev** [comment]
Hi @vsrboth ,

Are you experiencing long load times when using the terminal?

When using the Terminal, Ruby will print back the value of the last statement, which can take a very long time for PDF objects.

PDF objects are stored in a recursive Hash (some hash keys point to their parents). Your file will have a Hash with more then 500 Kb of data.

This will take `irb` a long time to process for printing.

You can avoid this slow "print" processing by giving `irb` a smaller object to print. 

i.e. the following line will print out the PDF Hash, which will take a long time:

```ruby
CombinePDF.load "test.pdf"
```

So, you can change it to the following line, which prints `nil`, which is fast:

```ruby
pdf = CombinePDF.load "test.pdf"; nil
```

Then you can use the data in the `pdf` variable to test out any actions you need. i.e.

```ruby
pdf.save "out.pdf"
```

Please tell me if this helps.

**Comment by vsrboth** [comment]
that's a magic ;) thank you so much @boazsegev

**Comment by boazsegev** [comment]
You're Welcome :)
