### ISSUE TITLE
Loading PDF files via an URL

### ISSUE THREAD

**Issue by chadwtaylor** [boazsegev/combine_pdf#62]
Awesome gem! Thanks for making this available.

Question: How do we load PDF files via an URL into CombinePDF.load?

**Comment by boazsegev** [comment]
Hi Chad, Thanks for the positive feedback.

As for loading PDF data from a URL, I would consider retrieving the file data and then parsing it using CombinePDF.parse`.

i.e.

```ruby
require 'combine_pdf'
require 'open-uri'

pdf = CombinePDF.parse open("http://www.istmt.rnu.tn/uploads/tb49mlcnad8o0lc.pdf").read
```

Good Luck!
