### ISSUE TITLE
NoMethodError - undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by tomascharad** [boazsegev/combine_pdf#63]
Hi @boazsegev ,
This error has presented to me.

This is the stack trace:
<pre style='color:#000000;background:#ffffff;'>combine_pdf <span style='color:#800080; '>(</span><span style='color:#008c00; '>0</span><span style='color:#800000; font-weight:bold; '>.</span><span style='color:#008c00; '>2</span><span style='color:#800000; font-weight:bold; '>.</span><span style='color:#008c00; '>16</span><span style='color:#800080; '>)</span> <span style='color:#40015a; '>lib/combine_pdf/page_methods.rb</span><span style='color:#808030; '>:</span><span style='color:#008c00; '>844</span><span style='color:#808030; '>:</span><span style='color:#800000; font-weight:bold; '>in</span> <span style='color:#000000; background:#ffffe8; '>`block </span><span style='color:#800080; background:#ffffe8; '>(</span><span style='color:#008c00; background:#ffffe8; '>2</span><span style='color:#000000; background:#ffffe8; '> levels</span><span style='color:#800080; background:#ffffe8; '>)</span><span style='color:#000000; background:#ffffe8; '> </span><span style='color:#800000; background:#ffffe8; font-weight:bold; '>in</span><span style='color:#000000; background:#ffffe8; '> should_secure</span><span style='color:#808030; background:#ffffe8; '>?</span><span style='color:#0000e6; background:#ffffe8; '>'</span>
<span style='color:#0000e6; background:#ffffe8; '>combine_pdf (0.2.16) lib/combine_pdf/page_methods.rb:844:in `block in should_secure?'</span><span style='color:#000000; background:#ffffe8; '></span>
<span style='color:#000000; background:#ffffe8; '>combine_pdf </span><span style='color:#800080; background:#ffffe8; '>(</span><span style='color:#008c00; background:#ffffe8; '>0</span><span style='color:#800000; background:#ffffe8; font-weight:bold; '>.</span><span style='color:#008c00; background:#ffffe8; '>2</span><span style='color:#800000; background:#ffffe8; font-weight:bold; '>.</span><span style='color:#008c00; background:#ffffe8; '>16</span><span style='color:#800080; background:#ffffe8; '>)</span><span style='color:#000000; background:#ffffe8; '> </span><span style='color:#40015a; background:#ffffe8; '>lib/combine_pdf/page_methods.rb</span><span style='color:#808030; background:#ffffe8; '>:</span><span style='color:#008c00; background:#ffffe8; '>842</span><span style='color:#808030; background:#ffffe8; '>:</span><span style='color:#800000; background:#ffffe8; font-weight:bold; '>in</span><span style='color:#000000; background:#ffffe8; '> `</span>should_secure<span style='color:#808030; '>?</span><span style='color:#0000e6; '>'</span>
<span style='color:#0000e6; '>combine_pdf (0.2.16) lib/combine_pdf/page_methods.rb:58:in `inject_page'</span>
combine_pdf <span style='color:#800080; '>(</span><span style='color:#008c00; '>0</span><span style='color:#800000; font-weight:bold; '>.</span><span style='color:#008c00; '>2</span><span style='color:#800000; font-weight:bold; '>.</span><span style='color:#008c00; '>16</span><span style='color:#800080; '>)</span> <span style='color:#40015a; '>lib/combine_pdf/page_methods.rb</span><span style='color:#808030; '>:</span><span style='color:#008c00; '>49</span><span style='color:#808030; '>:</span><span style='color:#800000; font-weight:bold; '>in</span> <span style='color:#000000; background:#ffffe8; '>`</span><span style='color:#e34adc; background:#ffffe8; '>&lt;</span><span style='color:#e34adc; background:#ffffe8; '>&lt;</span><span style='color:#0000e6; background:#ffffe8; '>'</span>
</pre>

This is caused by doing: 

`page << new_page`

The pdf is the following:

https://drive.google.com/file/d/0B3F-Rn6bPunbbkJDMmZjeEIxTlU/view?usp=sharing

**Comment by boazsegev** [comment]
Hi Tomás,

Thank you very much for exposing this issue, I'll look into this and try to write a patch as soon as I can.

B.

**Comment by boazsegev** [comment]
P.S.

Tomás, can you update to version 0.2.21 (latest release) and check if the issue persists?

**Comment by tomascharad** [comment]
Sorry @boazsegev , You are correct.
I updated and it works like a charm.
Many thanks!

**Comment by boazsegev** [comment]
Thanks for letting me know 👍 

It's better to have false positives then have bugs go unnoticed.
