### ISSUE TITLE
Can't open combined pdf

### ISSUE THREAD

**Issue by Zhong-z** [boazsegev/combine_pdf#64]
The error in Mac Preview says `It may be damaged or use a file format that Preview doesn't recgonize`. 
However when I tried to open in Chrome, only the first page showed, the rest pages are missing. 
Also tried in Firefox, the first page displayed fine, the rest pages showed as loading with a spinner.
The original pdfs were generated from Prawn 
I'm using 0.2.2 version.
ruby version 2.1.6p336

**Comment by boazsegev** [comment]
Hi Zhong Zheng,

Thank you for opening the issue and the example PDF files.

I can't seem to reproduce the issue using the latest version (version 0.2.21).

Can you update the version you're using and let me know if this resolves the issue?

If the issue persists after the update, can you send me the code you use for combining the PDF files (maybe the issue can be reproduced only when the PDF objects are combined in a specific way...)?

Thanks,
   B.

**Comment by Zhong-z** [comment]
The issue was solved using newest version. Somehow my brain converted 0.2.20 to 0.2.2(double to int?), and I thought the only difference from 0.2.21 is the typo in README file, so I didn't update to newest version.
Anyway, thank you very much for your help.

**Comment by boazsegev** [comment]
I'm happy it works for you :-)
