### ISSUE TITLE
Combine pdf issue with radio buttons.

### ISSUE THREAD

**Issue by joshirashmics** [boazsegev/combine_pdf#65]
Hi , I am trying to merge multiple dynamically filled pdf files using this gem. Everything else if working fine , except that the radio buttons are lost. By lost I mean, they are not present in the merged pdf.

I am attaching two files. 1) The actual pdf file. 2) The filled out pdf file. The forms in the actual pdf file (1) are filled using another ruby library pdftk to generate the output file (2).
Update 1) Even if I do not merge the pdf , a simple load and save results in the radio button getting lost.
 ```
def exportAndMerge(array_with_files_path_to_merging)
        original_file = CombinePDF.load(export)
        for file in array_with_files_path_to_merging
          original_file << CombinePDF.load(file)
        end
        output_path = "#{Rails.root}/lib/assets/temp_pdfs/#{SecureRandom.uuid}.pdf" # make sure tmp/pdfs exists
        original_file.save(output_path)
end
```

In the above code I passed an empty array as a parameter , which means I am simply loading and saving the pdf , but still the radio button is getting lost. The radio button was present in the pdf file dynamically generated through pdftk. 

I know the answer might be that pdftk is an old gem/library and the resultant pdf file is corrupted. However I would really appreciate a fix in combine_pdf as I have written lots of code to dynamically generate pdfs using pdftk, and moving to some other library might not be possible.

[filled output file.pdf](https://github.com/boazsegev/combine_pdf/files/329043/filled.output.file.pdf)
[PR g-325a.pdf](https://github.com/boazsegev/combine_pdf/files/329044/PR.g-325a.pdf)

**Comment by boazsegev** [comment]
Hi @joshirashmics ,

Thank you for opening this issue.

Originally, preserving form data wasn't part of the CombinePDF feature list, but it was added a few versions ago and I can reproduce the issue on my machine with the latest version... Which means this needs fixing. I'm looking into this, as I have no idea what causes the issue. It could an issue with annotations vs. form data, but I'm not sure...

If you find anything, let me know.

Again, thank you for pointing this out and discovering the issue.

Bo.

**Comment by joshirashmics** [comment]
Thanks @boazsegev  for confirming. I am relatively new to ruby , but I will see if I can find the cause.

**Comment by boazsegev** [comment]
There's a patched version on GitHub which I haven't fully tested yet.

Could you test that it works on your system and fixes the issues you experience?

I should note... form data conflicts are possible, if you're merging different forms, make sure they don't overlap.

Allow me to explain:

PDF uses global form names, so when updating a field, all the places where a field with the same name appears will show the update.

This is part of the PDF form data design.

If you merge PDF files with forms, these forms might collide, so it's possible a field's data will be overwritten.

Let me know how your experience goes. I hope this resolves your issue.

__p.s.__

If filling the form data doesn't work for you, consider writing text over the form using PDF#textbox. This will add text to the position on the page and that text will not be editable, nor will it conflict with other form data.

**Comment by joshirashmics** [comment]
Thanks @boazsegev , I will test it and let you know.

**Comment by joshirashmics** [comment]
Hi @boazsegev , I did the testing and it is working perfectly without any data conflicts (used unique name for each textfield to be safe) Thank you so much.

**Comment by boazsegev** [comment]
Thanks for keeping me posted, I'm ver happy it works for you :-)

I released the patch as version 0.2.22.

Good luck with your project!

**Comment by joshirashmics** [comment]
Thank you so much for all the effort you have put in this awesome gem!

**Comment by boazsegev** [comment]
@joshirashmics , you're very welcome :-)

Your appreciation is appreciated 👍
