### ISSUE TITLE
PDF is Encrypted! Attempting to decrypt - not yet fully supported.

### ISSUE THREAD

**Issue by kevshin2** [boazsegev/combine_pdf#66]
When I try to open a PDF, I got the following error. 
PDF is Encrypted! Attempting to decrypt - not yet fully supported.

I was able to open the file in preview without password. Any recommendation on how to solve this?

**Comment by boazsegev** [comment]
Hi Kevin, thank you for opening the issue.

Could you send me an example file to test this on?

I know Decryption support is limited, but you might have run into an issue with the implementation.

Bo.

**Comment by kevshin2** [comment]
Hi Bo,

The file attached would be a great example to test this on.

Thanks,
Kevin
 @boazsegev 
[odesza_nyc.pdf](https://github.com/boazsegev/combine_pdf/files/335484/odesza_nyc.pdf)

**Comment by boazsegev** [comment]
Thanks Kevin. 

It seems to be an issue related to PR #61 and has to do with the way the encryption parameters were stored (they were stored as references, and these references aren't resolved at that point in the logic-flow)...

... This requires a deeper change to the Decrypt module and I'm labeling it under Enhancement rather then a Bug... Although I would like to enhance the support for encrypted files, this feature is expected to fail for this group of encrypted files (encrypted files that store encryption data as references).

Hopefully, I will manage to write something soon.

**Comment by kevshin2** [comment]
Thanks Bo! Any idea if this will be an easy fix, combine_pdf has been working great for me so far, would love to know if a quick fix is possible before I have to move onto exploring other options. Thanks again

**Comment by boazsegev** [comment]
I've uploaded a fixed version, could you test it from GitHub before I release an update?

Please tell me if it works for you.

**Comment by kevshin2** [comment]
Hey Bo, it's working great! Thanks for the update!

One thing I realized is that, when calling pdf = CombinePDF.load("file.pdf"), pdf is being loaded into a data stream, pdf. number_pages doesn't work anymore.

Thanks!

**Comment by boazsegev** [comment]
Thank you for keeping me posted :-)

**Comment by kevshin2** [comment]
Please let me know when it's been released.

**Comment by pvin** [comment]
@kevshin2 @boazsegev I'm using version (1.0.16) and tried (1.0.21) also, but still getting this error **PDF is Encrypted! Attempting to decrypt - not yet fully supported.**

I'm able to open the file in preview without password. 

I see this issue, which is already discussed here and closed but still getting, any help here?

**Comment by boazsegev** [comment]
@pvin , Do you know if the file is encrypted? If it is, CombinePDF might not be able to decrypt it. 

Please note that passwords (authentication) have nothing to do with encryption, except that often both security measures are often used at the same time.
