### ISSUE TITLE
Parsing Error when merging pdf created with GNUPLOT from Ruby

### ISSUE THREAD

**Issue by peterlongfield** [boazsegev/combine_pdf#83]
[plotStudiesRMS.pdf](https://github.com/boazsegev/combine_pdf/files/426451/plotStudiesRMS.pdf)

Dear team.

I have been trying to merge a few pdf plots created by GNUPLOT from Ruby.

I can't make sense of the error message I receive. I don't know if it is a bug or if it is just me not understanding the situation/context/usage.

Let me know if I can help more. 
I can share with you the pdfs created by the attached script - which fails at merging them.

REgards

`C:/RUBY21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.30/lib/combine_pdf/parser.rb:203:in` `_parse_': Parsing Error: PDF file error - a stream object wasn't properly colsed usi
'endstream'! (RuntimeError)
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.30/lib/combine_pdf/parser.rb:75:in `parse'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.30/lib/combine_pdf/pdf_public.rb:94:in `initialize'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.30/lib/combine_pdf/api.rb:11:in `new'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/combine_pdf-0.2.30/lib/combine_pdf/api.rb:11:in `load'
        from plotStudiesRMS.rb:83:in `block (2 levels) in <main>'
        from plotStudiesRMS.rb:83:in `each'
        from plotStudiesRMS.rb:83:in `block in <main>'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:76:in `block in open'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:75:in `popen'
        from C:/RUBY21/lib/ruby/gems/2.1.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:75:in `open'
        from plotStudiesRMS.rb:45:in `<main>'
'

**Comment by peterlongfield** [comment]
Apologies for polluting this tracker ;-)
The bug came from GNuplot https://sourceforge.net/p/gnuplot/bugs/430/

Note though that the error message (in Combine_pdf) has a few typos :)

**Comment by boazsegev** [comment]
Thank you @peterlongfield for opening the issue.

I'm happy you found the source of the issue and I hope you found a way to resolve or work around it.

Let me know if you have any future questions.

Good luck with your project.
