### ISSUE TITLE
Combining PDF from action stream [question]

### ISSUE THREAD

**Issue by aussiDavid** [boazsegev/combine_pdf#84]
Hello,

I'm having trouble with creating a PDF from an action stream and merging it with CombinePDF.

The problem is described in the link below
[Stackoverflow - Rails Combining Pdfs From Action Stream](http://stackoverflow.com/questions/39268697/rails-combining-pdfs-from-action-stream)

I'd appreciate any help.

Thanks,

**Comment by boazsegev** [comment]
I posted some comments on SO, but I don't have enough information to help or even know if there's an error somewhere.

**Comment by aussiDavid** [comment]
Answer has been posted on Stackoverflow.

Thanks for your help :)
