### ISSUE TITLE
Format page numbers?

### ISSUE THREAD

**Issue by aussiDavid** [boazsegev/combine_pdf#85]
Is there a way to format the appearance of page numbers?

**Comment by boazsegev** [comment]
Yes.

See the documentation for both the [PDF#number_pages method](http://www.rubydoc.info/gems/combine_pdf/0.2.31/CombinePDF/PDF#number_pages-instance_method) and the [Page_Methods#textbox method](http://www.rubydoc.info/gems/combine_pdf/0.2.31/CombinePDF/Page_Methods#textbox-instance_method) for more details.
