### ISSUE TITLE
Corrupted pdf..

### ISSUE THREAD

**Issue by IonutPerfectWeb** [boazsegev/combine_pdf#87]
Hi! Thanks for this gem and congrats for the great job :) 

I integrated some plf splitting functionality using it, but have problems getting it to work in prod... 

the code is something like this: (this is an example)

```
existing_pdf = CombinePDF.parse(Net::HTTP.get_response(URI.parse(@document.content_url)).body)
pages_list = '1,2'.split(',')

new_pdf = CombinePDF.new

existing_pdf.pages.each_with_index do |page, index|
      page_nr = index + 1
      new_pdf << page if pages_list.include? page_nr.to_s
end

    @pdf = new_pdf.to_pdf
```

Locally this works great! But on prod, the result is this: https://we.tl/ppOdNtSg6Q (I linked to the original file, and the "Afterprocessing" file. Note that in this case, I just take the 2 pages pdf, and try to generate a new 2 page pdf using this code :) 

Thanks a lot!!!!!

**Comment by boazsegev** [comment]
Hi, Thanks for opening this issue.

Locally I can open and split the file (I didn't test your code yet), so I'm assuming the issue might be related to the `Net::HTTP.get_response URI.parse(@document.content_url)` part...

Could you send me a URL to test against?

Hopefully we can find a fix before the week is out.

**Comment by IonutPerfectWeb** [comment]
Thanks for the quick response. Yes, it had to do with that. On dev, there were no permissions to open that file, yet no error was raised. sorry for wasting your time, and thanks a lot for the quick resp! :)
