### ISSUE TITLE
Error parsing PDF from remote location using `CombinePDF.parse`

### ISSUE THREAD

**Issue by andela-echigbo** [boazsegev/combine_pdf#92]
Hello Guys! I'm having a problem parsing a PDF from the remote location. The README says to use **CombinePDF.parse** to load PDF data from memory and from remote location.

I have this in my code:
``` shell
CombinePDF.parse("https://daybear-dev.s3.amazonaws.com/landlord-notice/landlord-notice-facility-2.pdf", allow_optional_content: true)
```

...And I get this result:
``` shell
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
Warning: parser advancing for unknown reason. Potential data-loss.
RuntimeError: Unknown PDF parsing error - maleformed PDF file?
from /Users/emmanuelchigbo/.rvm/gems/ruby-2.3.1/gems/combine_pdf-0.2.31/lib/combine_pdf/parser.rb:78:in `parse'
```
_**maleformed PDF file**_ ?

I tried this with different PDF files and get the same error.
I also passed the `allow_optional_content` option but that still didn't help.

What am I doing wrong?

**Comment by boazsegev** [comment]
Hi @andela-echigbo ,

When using `parse`, the raw PDF data should be given (not the URL). For example:

```ruby
require 'combine_pdf'
require 'net/http'

url = "https://daybear-dev.s3.amazonaws.com/landlord-notice/landlord-notice-facility-2.pdf"
pdf = CombinePDF.parse Net::HTTP.get_response(URI.parse(url)).body
```

Some HTTP methods are faster than others, [such as pointed to here](http://stackoverflow.com/a/30343104/4025095).
Good Luck!

**Comment by boazsegev** [comment]
P.S.

Usually the response time for questions is better in [StackOverflow (SO)](http://stackoverflow.com), since more people are active at each given moment.

I hope this resolved your issue. Please let me know if experience any other issues with CombinePDF.

Good Luck!

**Comment by andela-echigbo** [comment]
It works like a charm @boazsegev. Thank you.

**Comment by adnanmirza1** [comment]
Hey, i'm facing the same issue. i'm trying to parse PDF stored in my active storage. with url_for
and facing this error
 CombinePDF::ParsingError Exception: Unknown PDF parsing error - malformed PDF file?

i'm using following syntax:
url = url_for(Candidate.last.pdf)
pdf = CombinePDF.parse(Net::HTTP.get_response(URI.parse(url)).body)

**Comment by marcosmcz** [comment]
I had this problem then I realized that using @boazsegev solutions of `URI.parse(s3_url)` would result with an XML object instead of a PDF when accessing an object without appropriate permissions/ CORS issues.

Two ways to fix this:

1. Make the object accessible to the internet i.e. remove all permissions on that S3 buckets object
2. Use the AWS S3 SDK to get the object and pass it as a string to be parsed using the `aws-sdk-s3` gem

```ruby
    s3 = Aws::S3::Client.new
    imported_pdf = s3.get_object(bucket: some_bucket, key: some_key)
    pdf_string = imported_pdf.body.string
    pdf = CombinePDF.parse(pdf_string)
```

Hope that helps
