### ISSUE TITLE
Watermarking gets covered?

### ISSUE THREAD

**Issue by tomascharad** [boazsegev/combine_pdf#95]
Hi @boazsegev, 

I'm not exactly sure what happens here. I'll try to explain this the best I can.

1. If you merge this two ([1](https://slack-files.com/T0CCB44TF-F39THMRC4-01f2e1659d), [2](https://slack-files.com/T0CCB44TF-F39U9AP7F-92fc529928)) documents, then as an example the watermarks are not displayed on page 26
<img width="730" alt="screen shot 2016-12-02 at 10 18 39 am" src="https://cloud.githubusercontent.com/assets/1534092/20835339/c67a3516-b878-11e6-9bee-83a8f2d7ce7d.png">

Have in mind that the file (1) already has some pages with watermarks.
2. If I use this tool https://smallpdf.com/split-pdf, and [extract just one page 26, or three](https://slack-files.com/T0CCB44TF-F39T1T1AQ-57ad9adecb), and I then combine it with the [watermark](https://slack-files.com/T0CCB44TF-F3AGPDA79-9f21f0fdc9), then [it works](https://slack-files.com/T0CCB44TF-F39546Q1W-204ccbd0fc)
<img width="742" alt="screen shot 2016-12-02 at 10 33 09 am" src="https://cloud.githubusercontent.com/assets/1534092/20835709/c20c7550-b87a-11e6-8670-db0e4ef9c963.png">

3. If I use this tool https://smallpdf.com/split-pdf, and extract pages 2-last, and I then combine it with the watermark, it doesn't work

Might be that watermarking is not working properly for too large files?
So I don't really know if this issue is related to the pdf itself,  or if it is something related with the combination process.

**Comment by boazsegev** [comment]
Oh... this one was a fun puzzle, took me a bit of time to find the issue...

It's all working correctly in theory. The issue is caused by this:

* Some pages in the PDF with the content are shorter than others.

     For example, page 0 (page 1) has the `mediabox` property of: [0, 0, 604, 931]

     On the other hand, page 23 (page 24) has the `mediabox` property of:  [0, 0, 604, 785]

     This is also true for the `cropbox` property.

* Because PDF files compute placement of objects from the bottom up (not top to bottom), this means that the top part of the data is hidden.

* The watermark page size is [0, 0, 604.0, 931.0].

* The watermark is hidden above the page limit.

* to expose the watermark, there are a few possible solution:

     1. Resize each page by setting both the `mediabox` and `cropbox` properties to be [0, 0, 604, 931].

     2. Create a watermark document with the correct page sizes for the expected PDF that you are watermarking.

     3. Use the [PDF#number_pages](http://www.rubydoc.info/gems/combine_pdf/0.2.32/CombinePDF/PDF#number_pages-instance_method) or the [Page#textbox](http://www.rubydoc.info/gems/combine_pdf/0.2.32/CombinePDF/Page_Methods#textbox-instance_method) to dynamically create the watermarks (assuming ASCII text watermarks). These functions should calculate the page size for each page separately.

Let me know if there's anything else I can help with.

Good luck!

**Comment by tomascharad** [comment]
You are a god!

**Comment by boazsegev** [comment]
Thanks! :-)
