### ISSUE TITLE
Bar codes do not automatically update after using combine_pdf.

### ISSUE THREAD

**Issue by joshirashmics** [boazsegev/combine_pdf#97]
I created bar codes on a  pdf form using the instructions found here:
https://helpx.adobe.com/acrobat/using/pdf-barcode-form-fields.html

Once my pdf is dnamically populated using [pdf-forms](https://github.com/jkraemer/pdf-forms) gem, I am combining the pdfs with combine_pdf. After the pdf goes through combine pdf , the barcode functionality of auto-updating the bar-code on form data change is lost.

The intermediate filled out pdf created using pdf-forms still has the functionality.

The issue exists even if I use a single pdf  with combine_pdf , and combine_pdf does not have to actually merge pdfs.

I have attached the file I use as a template. ( I added bar code just for the first page )
[g-28_applicant-temp.pdf](https://github.com/boazsegev/combine_pdf/files/741058/g-28_applicant-temp.pdf).

There is an app called pdf417 on itunes and google play store , that I use to get the bar code content.

Interestingly , once I go to edit the script used to generate barcode in acrobat pro and cut and paste the same script again , barcode auto updation starts happeening again.

Thanks.

PS: I have been using this gem for the last 8 months and appreciate the efforts put into it.

**Comment by boazsegev** [comment]
Hi @joshirashmics , thank you for opening this issue.

I'm very short on time, so I'll try to be brief. Please feel free to ask for any clarifications and I will do my best to find a good solution for this.

At some point in the past, when this gem was very young, I decided not to write support for interactive PDF objects, such as JavaScript. My application was receiving PDF data from clients and I was afraid to expose myself to PDF scripting attacks (yes, it was a thing at the time, it probably still is).

I'm not sure how Barcode works - is it a script? How does it produce the barcode interactively? Is it Javascript or a barcode specific feature?

The feature might be filtered for security reasons and it might be an oversight. I want to learn more, so we can find the best solution for this.

I read the link you sent me but I'm not sure yet how this barcode feature works. I would love any input you might have on the matter.

Until we can resolve this, I hope a workaround would be easy. I'm wondering if you could create a barcode overlay (perhaps using Prawn) from the form data? I think this will allow you more flexibility when you create each PDF. This way you can print the barcode both on the PDF (stamping it on the PDF using CombinePDF) and on any web-form feedback you might provide.

I know this isn't the best solution, but I hope it might work until we solve this.

**Comment by joshirashmics** [comment]
Thanks for response. We earlier used itext api to generate a bar code overlay image. However then our requirements changed and now we need to be able to update the bar code image dynamically as user makes changes to the geenrated pdf form data. 
So instead of generating the bar code image , we decided to embedd the bar code generating custom script in the pdf itself as described in the link above.
Here is a sample script 

```
 function strTabDelimited(oParam)
    {   var newValues = [];
        var strings =
        ["G-28",
        "05/05/16",
        "1",
       oParam.oDoc.getField("g28_applicant_representative_elis_account_no" ).value
        ];

       return "|" + strings.join("|") + "|";
    }

    try
    {
        if ( app.viewerVersion >= ADBE.PMD_Need_Version )
            event.value = strTabDelimited({oDoc: this});
        else event.value = " ";
    }
    catch (e)
    {
        event.value = " ";
    }
```

This Javascript has some adobe specific features. 
Like I said before this Javascript is still retained in the pdf generated by combine_pdf. In Acroabat , I can go to bar code propeties , edit the above custom calculation script and cut and paste the same JS again , and the bar code starts dynamically updating as user changes data in "g28_applicant_representative_elis_account_no" field.

**Comment by boazsegev** [comment]
Hi @joshirashmics ,

I updated some of the structures, though I'm still working on this.

Using the edge version (from GitHub), when I combine the PDFs the barcode still seems to work... but if I save the PDF after adding data using macOS Preview, the barcode breaks...

At the moment the only thing I can think about is that some of metadata is lost, which shouldn't effect usability and it shouldn't effect the way Preview is handling the PDF.

Can you test the latest unreleased version (the Github master repo)? 

Thanks again for opening the issue.

**Comment by joshirashmics** [comment]
Thanks. I will test this today evening one I get home. By edge version you mean the latest code from github right ?

**Comment by boazsegev** [comment]
Yes, the code on GitHub.

**Comment by joshirashmics** [comment]
Yes you mentioned in the last line , you are referring to master branch. 

While I am not at expert at pdf data structure , I just want to point out that the functionality of bar code automatically updating on form data change would work only on adobe pro ( they have a trial version) or on adobe reader if the pdf has a certain licence. This is what I read on certain adobe forum. This information might be old and outdated. 

I might be wrong so sorry for confusing you. Thanks again.

**Comment by joshirashmics** [comment]
Thank you so much @boazsegev . It worked pretty well. You have been a life saver for the second time (Bug #65 earlier) .
 There is one minor catch though. Upon downloading my barcode doesn't contain the data that I dynamically filled with "pdf-forms". I have to make a change in the data in order to make the javascript execute again and only then the bar code reloads with the correct data. The fact that barcode included static data on page load ( |G-28|05/05/16|1|(nothing here)| ) on page load indicates that the javascript had executed once on opening the pdf.

Thanks again for this wonderful gem.

**Comment by boazsegev** [comment]
@joshirashmics , you're very welcome.

I'm wondering if the issue you're experiencing is javascript related (a missing "on open" event of some kind?) or is it CombinePDF related...?

Does the catch exist only when you use CombinePDF?

**Comment by boazsegev** [comment]
P.S.

If the catch isn't CombinePDF related, I'll go ahead and release the updated version so it can be used in production.

**Comment by joshirashmics** [comment]
I don't think its related to combine_pdf. The issue occurs even with the
pdf generated with pdf_forms. Thanks again.

**Comment by boazsegev** [comment]
Good to know, thanks.

I've released the updated version.

Good Luck :)

**Comment by joshirashmics** [comment]
Thanks :) 👍
