### ISSUE TITLE
Is there a way to validate pdf files if they are able to be processed by combine_pdf?

### ISSUE THREAD

**Issue by maxpark-jd** [boazsegev/combine_pdf#98]
Hi, thank you for developing this gem. It is very useful.
Our app accepts user's uploaded pdf files and merge them into a pdf file using combine_pdf. Currently we are catching errors during the merge. It would be nice if we can validate if uploaded PDF files are processable by combine PDF upon uploading though. Is there a way to validate PDF files?

**Comment by boazsegev** [comment]
Hi @maxpark-jd ,

Thank you for opening this issue.

I'm not sure what errors you might be experiencing. If you offer some more details, maybe I could help.

There is no way to validate the PDF without opening the file.

To validate the PDF while uploading, I would test the file's extension (I would reject non-PDF uploads both using client side javascript and a server side validation of the file name) as well as attempt to open the PDF (if I get an exception, the PDF can't be processed).

For future reference, questions should be posted on [StackOverflow](http://stackoverflow.com). I'm not sure if this is about the errors or a feature request, so this is perfectly fine, but  [StackOverflow](http://stackoverflow.com) normally has more people with good ideas that can help you.

**Comment by maxpark-jd** [comment]
HI @boazsegev, thank you for a quick response! 

It was a question if the gem has any way (like a method) I can use to validate the PDF if it is processable as the description page reads it can have trouble with certain PDF files like encrypted or ones that couldn't be parsed. I would rather validate the files and reject them upon upload than letting the upload complete and issuing errors later.

I am already validating the extension on the front and backend. You mentioned there is no way to validate the file without opening it. Did you mean the 'load' method by 'opening'?

I am not sure if this question fits here or if you want me to bring it to stackoverflow.

**Comment by boazsegev** [comment]
Sorry for the delay, I had to go to class.

Yap. I meant the `CombinePDF.load` method... though I also meant that it's an expensive task that includes opening a file and reading it's contents.

As for the best place to open this discussion... Well, since it's a question, than most of the time you would get a faster response (and a larger variety of ideas) using StackOverflow.

**Comment by maxpark-jd** [comment]
Thank you @boazsegev !
